apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: v6opp214z-python
  janus-idp.io/tekton: v6opp214z-python
  backstage.io/kubernetes-id: v6opp214z-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: v6opp214z-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
